### ISSUE TITLE
Cannot join.

### ISSUE THREAD

**Issue by popkechupki** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#13]
ログイン時に「パックをサーバーと同期しています」で動かなくなる。
1.1.0対応作業用のbranchを作成しました。
https://github.com/JupiterDevelopmentTeam/JupiterDevelopmentTeam/tree/mcpe-1.1.0

**Comment by kazuemon** [comment]
CanとnotはCannotにすべきだと思います(どうでもいい)

**Comment by popkechupki** [comment]
変えましたｗ

**Comment by popkechupki** [comment]
修正されました。(a7bd4f6)
