### ISSUE TITLE
Jupiter独自の機能が現在使用できません

### ISSUE THREAD

**Issue by Megapix96** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#16]
Playerとかを全部コピーしたときにJupiterConfig機能を忘れていたためか、釣り竿やアイテムon/offなどの機能が飛んでしまった模様

**Comment by itsu020402** [comment]
v1.1.0ブランチでは保持されています。

**Comment by Megapix96** [comment]
mcpe-1.1.0では釣竿(関数じゃなくて使うときの)や
JupiterConfigのallow-系統が死んでると思います...

**Comment by itsu020402** [comment]
ありゃ

**Comment by itsu020402** [comment]
allow系統/Player算出メソッドは全て復帰しました。

**Comment by Megapix96** [comment]
本当にありがとうございます！
