### ISSUE TITLE
Jupiter.ymlを削除しないとクラッシュする

### ISSUE THREAD

**Issue by popkechupki** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#5]
起動時に新しくJupiter.ymlに追加された項目がJupiter.ymlに書き込まれずクラッシュします。
起動時にyml内の項目が追加された場合は自動で書き込むようにするべきだと思います。（そうしないならせめてファイルを削除して起動するよう説明するエラーメッセージを）

**Comment by itsu020402** [comment]
修正が完了しました。
jupiter.ymlがアップデートされていたら自動的に再生成されます。
